version: "3.3"
services:
  mysql:
    image: mysql
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: "ecommerce"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24